version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mall-mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: mall
      MYSQL_USER: mall
      MYSQL_PASSWORD: w7rsRh6c
    volumes:
      - mall-mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      mall:
        aliases:
          - mysql
    restart: always

volumes:
  mall-mysql:

networks:
  mall:
