package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallGroupon;
import me.vastpeng.mall.db.domain.MallGrouponExample;
import org.apache.ibatis.annotations.Param;

public interface MallGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    long countByExample(MallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(MallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int insert(MallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int insertSelective(MallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallGroupon selectOneByExample(MallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallGroupon selectOneByExampleSelective(@Param("example") MallGrouponExample example, @Param("selective") MallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallGroupon> selectByExampleSelective(@Param("example") MallGrouponExample example, @Param("selective") MallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    List<MallGroupon> selectByExample(MallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallGroupon record, @Param("example") MallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallGroupon record, @Param("example") MallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallGrouponExample example);
}