package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallIssue;
import me.vastpeng.mall.db.domain.MallIssueExample;
import org.apache.ibatis.annotations.Param;

public interface MallIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    long countByExample(MallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int deleteByExample(MallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int insert(MallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int insertSelective(MallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallIssue selectOneByExample(MallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallIssue selectOneByExampleSelective(@Param("example") MallIssueExample example, @Param("selective") MallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallIssue> selectByExampleSelective(@Param("example") MallIssueExample example, @Param("selective") MallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    List<MallIssue> selectByExample(MallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallIssue record, @Param("example") MallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallIssue record, @Param("example") MallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallIssueExample example);
}