package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallGoodsSpecification;
import me.vastpeng.mall.db.domain.MallGoodsSpecificationExample;
import org.apache.ibatis.annotations.Param;

public interface MallGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int insert(MallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(MallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallGoodsSpecification selectOneByExample(MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallGoodsSpecification selectOneByExampleSelective(@Param("example") MallGoodsSpecificationExample example, @Param("selective") MallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallGoodsSpecification> selectByExampleSelective(@Param("example") MallGoodsSpecificationExample example, @Param("selective") MallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    List<MallGoodsSpecification> selectByExample(MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallGoodsSpecification record, @Param("example") MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallGoodsSpecification record, @Param("example") MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallGoodsSpecificationExample example);
}