package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallCollect;
import me.vastpeng.mall.db.domain.MallCollectExample;
import org.apache.ibatis.annotations.Param;

public interface MallCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    long countByExample(MallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int deleteByExample(MallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int insert(MallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int insertSelective(MallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCollect selectOneByExample(MallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCollect selectOneByExampleSelective(@Param("example") MallCollectExample example, @Param("selective") MallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallCollect> selectByExampleSelective(@Param("example") MallCollectExample example, @Param("selective") MallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    List<MallCollect> selectByExample(MallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallCollect record, @Param("example") MallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallCollect record, @Param("example") MallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallCollectExample example);
}