package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallRole;
import me.vastpeng.mall.db.domain.MallRoleExample;
import org.apache.ibatis.annotations.Param;

public interface MallRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    long countByExample(MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int deleteByExample(MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int insert(MallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int insertSelective(MallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallRole selectOneByExample(MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallRole selectOneByExampleSelective(@Param("example") MallRoleExample example, @Param("selective") MallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallRole> selectByExampleSelective(@Param("example") MallRoleExample example, @Param("selective") MallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    List<MallRole> selectByExample(MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallRole record, @Param("example") MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallRole record, @Param("example") MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallRoleExample example);
}