package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallCouponUser;
import me.vastpeng.mall.db.domain.MallCouponUserExample;
import org.apache.ibatis.annotations.Param;

public interface MallCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int insert(MallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(MallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCouponUser selectOneByExample(MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCouponUser selectOneByExampleSelective(@Param("example") MallCouponUserExample example, @Param("selective") MallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallCouponUser> selectByExampleSelective(@Param("example") MallCouponUserExample example, @Param("selective") MallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    List<MallCouponUser> selectByExample(MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallCouponUser record, @Param("example") MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallCouponUser record, @Param("example") MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallCouponUserExample example);
}