package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallOrder;
import me.vastpeng.mall.db.domain.MallOrderExample;
import org.apache.ibatis.annotations.Param;

public interface MallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     */
    long countByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     */
    int deleteByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     */
    int insert(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     */
    int insertSelective(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallOrder selectOneByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallOrder selectOneByExampleSelective(@Param("example") MallOrderExample example, @Param("selective") MallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallOrder> selectByExampleSelective(@Param("example") MallOrderExample example, @Param("selective") MallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     */
    List<MallOrder> selectByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallOrder record, @Param("example") MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallOrder record, @Param("example") MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallOrderExample example);
}