package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallComment;
import me.vastpeng.mall.db.domain.MallCommentExample;
import org.apache.ibatis.annotations.Param;

public interface MallCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    long countByExample(MallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int deleteByExample(MallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int insert(MallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int insertSelective(MallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallComment selectOneByExample(MallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallComment selectOneByExampleSelective(@Param("example") MallCommentExample example, @Param("selective") MallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallComment> selectByExampleSelective(@Param("example") MallCommentExample example, @Param("selective") MallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    List<MallComment> selectByExample(MallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallComment record, @Param("example") MallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallComment record, @Param("example") MallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallCommentExample example);
}