package me.vastpeng.mall.db.dao;

import java.util.List;
import me.vastpeng.mall.db.domain.MallCoupon;
import me.vastpeng.mall.db.domain.MallCouponExample;
import org.apache.ibatis.annotations.Param;

public interface MallCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    long countByExample(MallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(MallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int insert(MallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int insertSelective(MallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCoupon selectOneByExample(MallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCoupon selectOneByExampleSelective(@Param("example") MallCouponExample example, @Param("selective") MallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallCoupon> selectByExampleSelective(@Param("example") MallCouponExample example, @Param("selective") MallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    List<MallCoupon> selectByExample(MallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallCoupon record, @Param("example") MallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallCoupon record, @Param("example") MallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallCouponExample example);
}