package me.vastpeng.mall.admin.util

object AdminResponseCode {
    val ADMIN_INVALID_NAME = 601
    val ADMIN_INVALID_PASSWORD = 602
    val ADMIN_NAME_EXIST = 602
    val ADMIN_ALTER_NOT_ALLOWED = 603
    val ADMIN_DELETE_NOT_ALLOWED = 604
    val ADMIN_INVALID_ACCOUNT = 605
    val GOODS_UPDATE_NOT_ALLOWED = 610
    val GOODS_NAME_EXIST = 611
    val ORDER_CONFIRM_NOT_ALLOWED = 620
    val ORDER_REFUND_FAILED = 621
    val ORDER_REPLY_EXIST = 622
    val USER_INVALID_NAME = 630
    val USER_INVALID_PASSWORD = 631
    val USER_INVALID_MOBILE = 632
    val USER_NAME_EXIST = 633
    val USER_MOBILE_EXIST = 634
    val ROLE_NAME_EXIST = 640
    val ROLE_SUPER_SUPERMISSION = 641
}